use crate::models::law::FullArticle;
use crate::services::gemini_client::{GeminiService, GenerationConfig};
use crate::verifier::jp_statutes::{
    all_admin_procedure_statutes, all_cca_statutes, all_commercial_statutes,
    all_constitution_statutes, all_construction_real_estate_statutes, all_environmental_statutes,
    all_ip_statutes, all_minpo_statutes, all_minpo_tort_statutes, all_pipa_statutes,
    all_sha_statutes,
};
use crate::verifier::jurisdiction::{DEFAULT_JURISDICTION, MultiJurisdictionMatcher};
use futures::future::join_all;
use legalis_core::{Condition, Effect, EffectType, Statute};
use legalis_dsl::LegalDslParser;
use legalis_jp::reasoning::{
    all_labor_statutes, lca_article_16_abusive_dismissal, lca_article_18_indefinite_conversion,
    lsa_article_20_dismissal_notice, lsa_article_32_working_hours, lsa_article_34_rest_periods,
    lsa_article_35_weekly_day_off, lsa_article_36_overtime_agreement,
    lsa_article_37_overtime_premium, lsa_article_39_annual_leave, minimum_wage_act,
    overtime_limit_regulation,
};
use std::sync::{Arc, Mutex};
use tokio::sync::Semaphore;
use tracing::{debug, warn};

/// Source of a converted statute.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConversionSource {
    /// Matched from legalis-jp pre-built domain statutes (instant, no API cost).
    Domain,
    /// Generated by Gemini LLM → parsed through LegalDslParser.
    Llm,
    /// Fallback: article text converted to Condition::Custom (never fails).
    Fallback,
}

/// A statute derived from a FullArticle with provenance metadata.
#[derive(Debug, Clone)]
pub struct ArticleStatute {
    /// The article that produced this statute.
    pub article_id: String,
    /// The resulting Statute object.
    pub statute: Statute,
    /// How the statute was produced.
    pub source: ConversionSource,
}

/// Maps Japanese law title keywords → pre-built Statute objects from legalis-jp.
///
/// Path 1 of the hybrid bridge (instant, no API cost, highest quality).
pub struct JpDomainMatcher;

impl JpDomainMatcher {
    /// Returns statutes from legalis-jp if the law title matches a known domain.
    /// Returns `None` when no domain match is found.
    #[must_use]
    pub fn match_law_title(law_title: &str) -> Option<Vec<Statute>> {
        // Labor Standards Act (労働基準法)
        if law_title.contains("労働基準法") {
            return Some(vec![
                lsa_article_32_working_hours(),
                lsa_article_34_rest_periods(),
                lsa_article_35_weekly_day_off(),
                lsa_article_36_overtime_agreement(),
                lsa_article_37_overtime_premium(),
                lsa_article_20_dismissal_notice(),
                lsa_article_39_annual_leave(),
                overtime_limit_regulation(),
            ]);
        }

        // Labor Contract Act (労働契約法)
        if law_title.contains("労働契約法") {
            return Some(vec![
                lca_article_18_indefinite_conversion(),
                lca_article_16_abusive_dismissal(),
            ]);
        }

        // Minimum Wage Act (最低賃金法)
        if law_title.contains("最低賃金") {
            return Some(vec![minimum_wage_act()]);
        }

        // Broad labor law queries — return all labor statutes
        if law_title.contains("労働") && law_title.contains("法") {
            return Some(all_labor_statutes());
        }

        // Overtime limit regulation (働き方改革)
        if law_title.contains("働き方改革") || law_title.contains("時間外労働") {
            return Some(vec![
                overtime_limit_regulation(),
                lsa_article_36_overtime_agreement(),
                lsa_article_37_overtime_premium(),
            ]);
        }

        // Fixed-term conversion queries (無期転換)
        if law_title.contains("無期転換") || law_title.contains("有期雇用") {
            return Some(vec![
                lca_article_18_indefinite_conversion(),
                lca_article_16_abusive_dismissal(),
            ]);
        }

        // Personal Information Protection Act (個人情報保護法)
        if law_title.contains("個人情報") {
            return Some(all_pipa_statutes());
        }

        // Subcontracting Act (下請法 / 下請代金支払遅延等防止法)
        if law_title.contains("下請") {
            return Some(all_sha_statutes());
        }

        // Consumer Contract Act (消費者契約法)
        if law_title.contains("消費者契約") {
            return Some(all_cca_statutes());
        }

        // Intellectual Property (著作権法 / 特許法 / 知的財産 / 商標法).
        // Checked before generic civil-code keywords so 著作権 maps to the IP set.
        if law_title.contains("著作権")
            || law_title.contains("特許")
            || law_title.contains("知的財産")
            || law_title.contains("商標")
        {
            return Some(all_ip_statutes());
        }

        // Commercial Code / Companies Act (会社法 / 商法)
        if law_title.contains("会社法") || law_title.contains("商法") {
            return Some(all_commercial_statutes());
        }

        // Constitution of Japan (憲法)
        if law_title.contains("憲法") {
            return Some(all_constitution_statutes());
        }

        // Environmental Law (環境法 / 大気汚染防止法 / 水質汚濁防止法 / 廃棄物処理法 / 公害)
        if law_title.contains("環境")
            || law_title.contains("大気汚染")
            || law_title.contains("水質汚濁")
            || law_title.contains("廃棄物")
            || law_title.contains("公害")
        {
            return Some(all_environmental_statutes());
        }

        // Administrative Procedure Act (行政手続法 / 行政指導)
        if law_title.contains("行政手続") || law_title.contains("行政指導") {
            return Some(all_admin_procedure_statutes());
        }

        // Construction Business / Real Estate Brokerage (建設業法 / 宅地建物取引業法 / 宅建)
        if law_title.contains("建設業")
            || law_title.contains("宅地建物取引")
            || law_title.contains("宅建")
        {
            return Some(all_construction_real_estate_statutes());
        }

        // Civil Code tort (不法行為 / 損害賠償 / 使用者責任) → minpo Art.709/710/715(1).
        // Placed before the generic 民法 branch so a tort-specific title returns the
        // focused tort subset, while plain 民法 returns the comprehensive set below.
        if law_title.contains("不法行為")
            || law_title.contains("損害賠償")
            || law_title.contains("使用者責任")
        {
            return Some(all_minpo_tort_statutes());
        }

        // Civil Code (民法) — comprehensive set (tort + general/contract provisions)
        if law_title.contains("民法") {
            return Some(all_minpo_statutes());
        }

        None
    }

    /// Returns `true` if this law title has domain-matched statutes.
    #[must_use]
    pub fn has_domain_match(law_title: &str) -> bool {
        Self::match_law_title(law_title).is_some()
    }
}

/// Translates raw Japanese article text → DSL text via Gemini, then parses.
///
/// Path 2 of the hybrid bridge (fallback for unknown domains).
pub struct DslTranslator {
    parser: Mutex<LegalDslParser>,
}

impl Default for DslTranslator {
    fn default() -> Self {
        Self::new()
    }
}

impl DslTranslator {
    #[must_use]
    pub fn new() -> Self {
        Self {
            parser: Mutex::new(LegalDslParser::new()),
        }
    }

    /// Ask Gemini to convert a Japanese article into Legalis DSL format.
    /// On parse failure, constructs a fallback `Condition::Custom` statute.
    pub async fn translate_article(
        &self,
        article: &FullArticle,
        gemini: &GeminiService,
    ) -> (Statute, ConversionSource) {
        let dsl_text = self.call_gemini_for_dsl(article, gemini).await;

        if let Some(dsl) = dsl_text {
            let parser = self.parser.lock().unwrap_or_else(|p| p.into_inner());
            match parser.parse_statute(&dsl) {
                Ok(statute) => {
                    debug!("DSL parse succeeded for article {}", article.unique_anchor);
                    return (statute, ConversionSource::Llm);
                }
                Err(e) => {
                    debug!(
                        "DSL parse failed for {}: {} — using fallback",
                        article.unique_anchor, e
                    );
                }
            }
        }

        // Fallback: construct statute from article text
        (
            self.make_fallback_statute(article),
            ConversionSource::Fallback,
        )
    }

    /// Calls Gemini to generate Legalis DSL for the given article.
    async fn call_gemini_for_dsl(
        &self,
        article: &FullArticle,
        gemini: &GeminiService,
    ) -> Option<String> {
        let system = DSL_SYSTEM_PROMPT;
        let content = article.content.chars().take(800).collect::<String>();
        let input = format!(
            "以下の日本語条文をLegalis DSL形式に変換してください。\n条文タイトル: {}\n条文本文:\n{}\n\nLegalis DSL:",
            article.title, content
        );

        let gen_config = GenerationConfig {
            temperature: 0.0,
            max_output_tokens: 512,
            top_p: 1.0,
            top_k: 1,
            candidate_count: 1,
        };

        match gemini.call_strict(&input, system, &gen_config).await {
            Ok(resp) => {
                let text = resp.text.trim().to_string();
                if text.contains("STATUTE") && text.contains("THEN") {
                    Some(text)
                } else {
                    debug!(
                        "Gemini DSL response missing STATUTE/THEN for {} — using fallback",
                        article.unique_anchor
                    );
                    None
                }
            }
            Err(e) => {
                warn!(
                    "Gemini DSL translation failed for {}: {}",
                    article.unique_anchor, e
                );
                None
            }
        }
    }

    /// Construct a fallback Statute that always represents the article
    /// as a `Condition::Custom` so the pipeline never returns zero statutes.
    fn make_fallback_statute(&self, article: &FullArticle) -> Statute {
        let id = sanitize_id(&article.unique_anchor);
        let title = article.title.chars().take(80).collect::<String>();
        let description = article.content.chars().take(200).collect::<String>();

        Statute::new(
            id,
            title,
            Effect::new(
                EffectType::Custom,
                article.content.chars().take(100).collect::<String>(),
            ),
        )
        .with_precondition(Condition::Custom { description })
        .with_jurisdiction("JP")
    }
}

/// Sanitize a string into a valid Legalis DSL identifier.
/// IDs may only contain ASCII alphanumeric characters, hyphens, and underscores.
fn sanitize_id(raw: &str) -> String {
    raw.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

/// Orchestrates the hybrid domain-matching + LLM-to-DSL bridge.
///
/// Conversion order:
/// 1. Check if the law title matches a legalis-jp domain → return all domain statutes
/// 2. For each unmatched article: try Gemini DSL translation
/// 3. Fallback to `Condition::Custom` (never fails, always produces ≥1 statute)
pub struct StatuteBridge {
    translator: DslTranslator,
    jurisdictions: MultiJurisdictionMatcher,
}

impl Default for StatuteBridge {
    fn default() -> Self {
        Self::new()
    }
}

impl StatuteBridge {
    #[must_use]
    pub fn new() -> Self {
        Self {
            translator: DslTranslator::new(),
            jurisdictions: MultiJurisdictionMatcher::new(),
        }
    }

    /// Convert a batch of articles into `ArticleStatute` objects (jurisdiction `"JP"`).
    ///
    /// - Domain-matched articles return statutes without an API call.
    /// - Others go through Gemini DSL translation with a custom fallback.
    ///
    /// Thin wrapper over [`Self::convert_articles_for`] preserving the JP default.
    pub async fn convert_articles(
        &self,
        articles: &[FullArticle],
        gemini: &GeminiService,
    ) -> Vec<ArticleStatute> {
        self.convert_articles_for(articles, gemini, DEFAULT_JURISDICTION)
            .await
    }

    /// Convert a batch of articles into `ArticleStatute` objects for `jurisdiction`.
    ///
    /// Domain matching is dispatched through [`MultiJurisdictionMatcher`]; the
    /// code is normalized first (empty/unknown → `"JP"`). Unmatched articles fall
    /// through to Gemini DSL translation with a `Condition::Custom` fallback.
    pub async fn convert_articles_for(
        &self,
        articles: &[FullArticle],
        gemini: &GeminiService,
        jurisdiction: &str,
    ) -> Vec<ArticleStatute> {
        let code = self.jurisdictions.normalize_code(jurisdiction);
        let mut results: Vec<ArticleStatute> = vec![];

        // Separate domain-matched articles from those needing LLM translation.
        let mut domain_matched_titles: std::collections::HashSet<String> =
            std::collections::HashSet::new();
        let mut llm_articles: Vec<&FullArticle> = vec![];

        for article in articles {
            if let Some(statutes) = self.jurisdictions.match_for(&code, &article.title) {
                if domain_matched_titles.insert(article.title.clone()) {
                    debug!(
                        "Domain match [{}]: {} → {} statutes",
                        code,
                        article.title,
                        statutes.len()
                    );
                    for statute in statutes {
                        results.push(ArticleStatute {
                            article_id: article.unique_anchor.clone(),
                            statute,
                            source: ConversionSource::Domain,
                        });
                    }
                }
            } else {
                llm_articles.push(article);
            }
        }

        // Run LLM translations with bounded concurrency to avoid Gemini rate limits.
        // Semaphore caps simultaneous in-flight API calls to MAX_CONCURRENT_GEMINI.
        const MAX_CONCURRENT_GEMINI: usize = 5;

        if !llm_articles.is_empty() {
            debug!(
                "Running {} Gemini DSL translations (max {} concurrent)",
                llm_articles.len(),
                MAX_CONCURRENT_GEMINI
            );
            let semaphore = Arc::new(Semaphore::new(MAX_CONCURRENT_GEMINI));
            let translator = Arc::new(&self.translator);
            let futs = llm_articles.iter().map(|article| {
                let translator = Arc::clone(&translator);
                let semaphore = Arc::clone(&semaphore);
                async move {
                    let _permit = semaphore
                        .acquire()
                        .await
                        .expect("semaphore closed unexpectedly");
                    let (statute, source) = translator.translate_article(article, gemini).await;
                    ArticleStatute {
                        article_id: article.unique_anchor.clone(),
                        statute,
                        source,
                    }
                }
            });
            let llm_results = join_all(futs).await;
            results.extend(llm_results);
        }

        results
    }

    /// Quick synchronous conversion using only domain matching (no API calls),
    /// for jurisdiction `"JP"`.
    ///
    /// Used when Gemini is unavailable or for testing. Thin wrapper over
    /// [`Self::convert_articles_domain_only_for`] preserving the JP default.
    #[must_use]
    pub fn convert_articles_domain_only(articles: &[FullArticle]) -> Vec<ArticleStatute> {
        Self::convert_articles_domain_only_for(articles, DEFAULT_JURISDICTION)
    }

    /// Quick synchronous conversion using only domain matching (no API calls),
    /// for an arbitrary `jurisdiction`.
    ///
    /// Domain matching is dispatched through [`MultiJurisdictionMatcher`] (code
    /// normalized first). Unmatched articles get a `Condition::Custom` fallback
    /// statute so the result is never empty.
    #[must_use]
    pub fn convert_articles_domain_only_for(
        articles: &[FullArticle],
        jurisdiction: &str,
    ) -> Vec<ArticleStatute> {
        let jurisdictions = MultiJurisdictionMatcher::new();
        let code = jurisdictions.normalize_code(jurisdiction);
        let mut results = vec![];
        let mut seen_titles = std::collections::HashSet::new();

        for article in articles {
            if let Some(statutes) = jurisdictions.match_for(&code, &article.title) {
                if seen_titles.insert(article.title.clone()) {
                    for statute in statutes {
                        results.push(ArticleStatute {
                            article_id: article.unique_anchor.clone(),
                            statute,
                            source: ConversionSource::Domain,
                        });
                    }
                }
            } else {
                // Fallback inline
                let translator = DslTranslator::new();
                let statute = translator.make_fallback_statute(article);
                results.push(ArticleStatute {
                    article_id: article.unique_anchor.clone(),
                    statute,
                    source: ConversionSource::Fallback,
                });
            }
        }

        results
    }
}

/// System prompt for Gemini DSL translation.
const DSL_SYSTEM_PROMPT: &str = r#"You are a legal formalization assistant.
Convert Japanese statute text to Legalis DSL format.

DSL grammar:
  STATUTE <id>: "<title>" {
    WHEN <condition>
    THEN <effect-type> "<description>"
  }

effect-type: GRANT | OBLIGATION | PROHIBITION | REVOKE
condition examples:
  AGE >= 18
  DURATION >= 60 MONTHS
  ATTRIBUTE "employment_type" == "fixed_term"
  HAS "license"

Output ONLY the DSL, no explanation. Use ASCII-safe identifiers (letters, digits, hyphens).

Example:
  STATUTE adult-voting: "Voting Rights (Art. 15)" {
    WHEN AGE >= 18
    THEN GRANT "Right to vote in national elections"
  }
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::law::FullArticle;

    fn make_article(title: &str, content: &str) -> FullArticle {
        FullArticle {
            law_id: "test_id".to_string(),
            title: title.to_string(),
            content: content.to_string(),
            unique_anchor: "Article_1".to_string(),
            anchor: None,
            url: "https://example.com".to_string(),
        }
    }

    #[test]
    fn test_domain_matcher_labor_standards() {
        let statutes = JpDomainMatcher::match_law_title("労働基準法");
        assert!(statutes.is_some());
        let statutes = statutes.unwrap();
        assert!(!statutes.is_empty());
        // Should contain LSA_Art32 (working hours)
        assert!(statutes.iter().any(|s| s.id == "LSA_Art32"));
    }

    #[test]
    fn test_domain_matcher_labor_contract() {
        let statutes = JpDomainMatcher::match_law_title("労働契約法");
        assert!(statutes.is_some());
        let statutes = statutes.unwrap();
        assert!(statutes.iter().any(|s| s.id == "LCA_Art18"));
    }

    #[test]
    fn test_domain_matcher_no_match() {
        // 道路交通法 is intentionally outside every covered domain.
        let result = JpDomainMatcher::match_law_title("道路交通法");
        assert!(result.is_none());
    }

    #[test]
    fn test_domain_matcher_minimum_wage() {
        let result = JpDomainMatcher::match_law_title("最低賃金法");
        assert!(result.is_some());
        assert!(result.unwrap().iter().any(|s| s.id == "MWA"));
    }

    #[test]
    fn test_domain_matcher_overtime() {
        let result = JpDomainMatcher::match_law_title("時間外労働の上限規制に関する法律");
        assert!(result.is_some());
    }

    #[test]
    fn test_domain_matcher_minpo() {
        let statutes = JpDomainMatcher::match_law_title("民法");
        assert!(statutes.is_some());
        let statutes = statutes.unwrap();
        // The Civil Code set reuses the legalis-jp tort article 709 and adds general provisions
        assert!(statutes.iter().any(|s| s.id == "minpo-709"));
        assert!(statutes.iter().any(|s| s.id == "Minpo_Art415"));
    }

    #[test]
    fn test_domain_matcher_tort() {
        // 不法行為 / 損害賠償 keywords map to the focused minpo tort articles.
        let statutes = JpDomainMatcher::match_law_title("不法行為に基づく損害賠償請求");
        assert!(statutes.is_some());
        let statutes = statutes.unwrap();
        assert_eq!(statutes.len(), 3);
        assert!(statutes.iter().any(|s| s.id == "minpo-709"));
        assert!(statutes.iter().any(|s| s.id == "minpo-715-1"));
    }

    #[test]
    fn test_domain_matcher_commercial() {
        let statutes = JpDomainMatcher::match_law_title("会社法");
        assert!(statutes.is_some());
        assert!(
            statutes
                .unwrap()
                .iter()
                .any(|s| s.id == "CompaniesAct_Art423")
        );
        // 商法 maps to the same commercial set.
        assert!(JpDomainMatcher::has_domain_match("商法"));
    }

    #[test]
    fn test_domain_matcher_constitution() {
        let statutes = JpDomainMatcher::match_law_title("日本国憲法");
        assert!(statutes.is_some());
        assert!(statutes.unwrap().iter().any(|s| s.id == "Const_Art13"));
    }

    #[test]
    fn test_domain_matcher_intellectual_property() {
        // 著作権法 was previously unmatched; it now maps to the IP set.
        let copyright = JpDomainMatcher::match_law_title("著作権法");
        assert!(copyright.is_some());
        assert!(copyright.unwrap().iter().any(|s| s.id == "Copyright_Art21"));
        // 特許法 maps to the same IP set with patent articles present.
        let patent = JpDomainMatcher::match_law_title("特許法 第68条");
        assert!(patent.is_some());
        assert!(patent.unwrap().iter().any(|s| s.id == "Patent_Art68"));
    }

    #[test]
    fn test_domain_matcher_environmental() {
        let statutes = JpDomainMatcher::match_law_title("大気汚染防止法");
        assert!(statutes.is_some());
        assert!(
            statutes
                .unwrap()
                .iter()
                .any(|s| s.id == "AirPollution_Art13")
        );
        assert!(JpDomainMatcher::has_domain_match("環境基本法"));
    }

    #[test]
    fn test_domain_matcher_administrative_procedure() {
        let statutes = JpDomainMatcher::match_law_title("行政手続法");
        assert!(statutes.is_some());
        assert!(statutes.unwrap().iter().any(|s| s.id == "AdminProc_Art5"));
    }

    #[test]
    fn test_domain_matcher_construction_real_estate() {
        let real_estate = JpDomainMatcher::match_law_title("宅地建物取引業法");
        assert!(real_estate.is_some());
        assert!(
            real_estate
                .unwrap()
                .iter()
                .any(|s| s.id == "RealEstate_Art35")
        );
        // 建設業法 maps to the same set with construction articles present.
        let construction = JpDomainMatcher::match_law_title("建設業法 第19条");
        assert!(construction.is_some());
        assert!(
            construction
                .unwrap()
                .iter()
                .any(|s| s.id == "Construction_Art3")
        );
    }

    #[test]
    fn test_fallback_statute_construction() {
        let article = make_article(
            "著作権法 第1条",
            "この法律は著作物の利用に関して著作者の権利を定める。",
        );
        let translator = DslTranslator::new();
        let statute = translator.make_fallback_statute(&article);
        assert!(!statute.id.is_empty());
        assert!(!statute.title.is_empty());
    }

    #[test]
    fn test_domain_only_conversion() {
        let articles = vec![
            make_article(
                "労働基準法 第32条",
                "1日8時間を超えて労働させてはならない。",
            ),
            // 道路交通法 is outside every covered domain → exercises the Fallback path.
            make_article(
                "道路交通法 第1条",
                "車両は信号機の表示に従わなければならない。",
            ),
        ];
        let results = StatuteBridge::convert_articles_domain_only(&articles);
        assert!(!results.is_empty());
        // First article (labor law) should be Domain, second should be Fallback
        assert!(results.iter().any(|r| r.source == ConversionSource::Domain));
        assert!(
            results
                .iter()
                .any(|r| r.source == ConversionSource::Fallback)
        );
    }

    #[test]
    fn test_domain_only_conversion_eu() {
        // With jurisdiction "EU", a GDPR title resolves to EU-tagged statutes.
        let articles = vec![make_article(
            "GDPR personal data processing",
            "Regulation (EU) 2016/679 governs the processing of personal data.",
        )];
        let results = StatuteBridge::convert_articles_domain_only_for(&articles, "EU");
        assert!(!results.is_empty());
        assert!(results.iter().any(|r| r.source == ConversionSource::Domain));
        assert!(
            results
                .iter()
                .all(|r| r.statute.jurisdiction.as_deref() == Some("EU"))
        );
    }

    #[test]
    fn test_sanitize_id() {
        assert_eq!(sanitize_id("Article_1"), "Article_1");
        // Japanese chars → hyphens, underscore preserved, trimmed
        let jp_id = sanitize_id("労働基準法_第32条");
        assert!(!jp_id.is_empty());
        assert!(!jp_id.starts_with('-'));
        assert!(!jp_id.ends_with('-'));
        // Leading/trailing hyphens should be trimmed
        let id = sanitize_id("--test--");
        assert_eq!(id, "test");
    }

    #[test]
    fn test_has_domain_match() {
        assert!(JpDomainMatcher::has_domain_match("労働基準法"));
        assert!(!JpDomainMatcher::has_domain_match("道路交通法"));
    }

    #[test]
    fn test_domain_only_no_duplicates() {
        // Same law_title appears in multiple articles → domain statutes inserted only once
        let articles = vec![
            make_article("労働基準法 第32条", "1日8時間の上限"),
            make_article("労働基準法 第36条", "36協定について"),
        ];
        let results = StatuteBridge::convert_articles_domain_only(&articles);
        // The duplicate title "労働基準法" is detected but article titles differ
        // Each unique title triggers one batch of domain statutes
        assert!(!results.is_empty());
    }
}
